/* Create a vehicle class function, which can be used to create vehicle objects by given parameters. The 
vehicle objects should have the following properties - example values:
    type – truck(string)
    tireCount – 6(number)
    capacity – 5 (number)    
   */
  class Car {
      type: string;
      tireCount: number;
      capacity: number;

      constructor (
         type: string,
         tireCount: number,
         capacity: number
      )
      {
         this.type = type;
         this.tireCount = tireCount;
         this.capacity = capacity;
      }
/*       carType() {
         console.log(`The car type is ${this.type}`);
      } */
  }

  
   let car1 = new Car("truck", 6, 5);
   let car2 = new Car("personalcar", 4, 5);
   let car3 = new Car("motobyke", 2, 1);
   let car4 = new Car("truck", 6, 5);
   let car5 = new Car("personalcar", 4, 5);
   let car6 = new Car("motobyke", 2, 1);
   let car7 = new Car("truck", 6, 5);
   let car8 = new Car("personalcar", 4, 5);
   let car9 = new Car("motobyke", 2, 1);
   let car10 = new Car("truck", 6, 5);
   


/* Create a loop which creates 10 vehicle objects with random values for the properties.
   Random values can be generated by using the Math.random() function.
   The loop should store the created vehicle objects in an array */
  const typeArray =["truck", "personalcar", "motobyke", "truck", "personalcar", "motobyke", 
   "truck", "personalcar", "motobyke", "truck"]
  let carArray: Car[] = [];
  function getRandomThing() {
   for (let i=0; i<10; i++) {
      let randomType = typeArray[Math.floor(Math.random()*type.length)]; 
      let tireCount = Math.floor(Math.random() * 10);
      let  randomCap = Math.floor(Math.random() * 10);
      let vehicle = new Car(randomType, tireCount, randomCap); 
      carArray.push(vehicle);   
      console.log(carArray);
    }
  }
   getRandomThing();
 
/* Create a function which accepts an array of vehicles as a parameter and 
   prints the types of the vehicles to the console */
   function printCarType(typeArray: Car[]) {
      for (let i=0; i<typeArray.length; i++) {
         console.log(typeArray[i].type);
      }
   }
printCarType(carArray);